version: '3.8'

services:
  frontend:
    platform: linux/arm64
    image: gsemir/account-app-frontend:0.2.0
    container_name: account-app-frontend
    ports:
      - "70:80"
    restart: on-failure
    networks:
      - account-app-network

  backend:
    platform: linux/arm64
    image: gsemir/account-app-backend:0.1.1
    container_name: account-app-backend
    ports:
      - "7070:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    networks:
      - account-app-network

  db:
    image: mysql:latest
    container_name: account-app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: on-failure
    networks:
      - account-app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

networks:
  account-app-network:
    driver: bridge

volumes:
  mysql-data:
